version: "3.9"
services:
  rabbitmq1:
    image: rabbitmq:3-management
    hostname: rabbitmq1
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq1
    networks:
      - rabbitmq-cluster
    ports:
      - "15672:15672"

  rabbitmq2:
    image: rabbitmq:3-management
    hostname: rabbitmq2
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq2
    networks:
      - rabbitmq-cluster
    depends_on:
      - rabbitmq1

  rabbitmq3:
    image: rabbitmq:3-management
    hostname: rabbitmq3
    environment:
      - RABBITMQ_ERLANG_COOKIE=my-secret-cookie
      - RABBITMQ_NODENAME=rabbitmq3
    networks:
      - rabbitmq-cluster
    depends_on:
      - rabbitmq1

networks:
  rabbitmq-cluster:
